2020-05-03 10:40:38,539 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 10:42:25,569 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 10:42:56,786 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 10:45:04,275 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 10:45:09,191 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 13:20:20,552 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 13:20:57,017 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 13:21:13,764 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 13:21:21,236 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 13:21:42,547 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 13:22:07,881 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 13:22:14,709 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 13:23:43,221 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 13:24:09,973 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 13:24:19,377 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 13:24:39,175 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 13:25:12,413 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 13:26:51,825 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 13:26:56,848 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 13:27:53,030 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 13:29:16,840 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 13:29:32,513 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 13:37:30,600 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 13:38:14,429 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 13:38:19,386 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 13:52:54,792 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 13:56:32,746 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 13:58:47,215 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 13:59:02,670 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 14:00:40,624 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 14:16:54,169 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 14:17:39,000 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 14:18:02,723 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 14:18:10,131 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 14:18:15,438 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 14:18:23,775 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 14:19:25,895 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 14:31:56,631 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 14:32:03,935 ERROR: Exception on /GlobalTalk [GET] [in C:\Users\User\Desktop\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\User\Desktop\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\Desktop\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\Desktop\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\Desktop\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\User\Desktop\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\Desktop\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\User\Desktop\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\User\Desktop\microblog\app\main\routes.py", line 210, in GlobalTalk
    GTFunction = GlobalTalk.query.all()
AttributeError: 'function' object has no attribute 'query'
2020-05-03 14:33:22,728 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 14:33:24,404 ERROR: Exception on /GlobalTalk [GET] [in C:\Users\User\Desktop\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\User\Desktop\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\Desktop\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\Desktop\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\Desktop\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\User\Desktop\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\Desktop\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\User\Desktop\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\User\Desktop\microblog\app\main\routes.py", line 210, in GlobalTalk
    GTFunction = GlobalTalk.query.all()
AttributeError: 'function' object has no attribute 'query'
2020-05-03 14:34:55,240 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 14:34:56,691 ERROR: Exception on /GlobalTalk [GET] [in C:\Users\User\Desktop\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\User\Desktop\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\Desktop\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\Desktop\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\Desktop\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\User\Desktop\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\Desktop\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\User\Desktop\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\User\Desktop\microblog\app\main\routes.py", line 210, in GlobalTalk
    GTFunction = GlobalTalk.query.all()
AttributeError: 'function' object has no attribute 'query'
2020-05-03 14:35:59,737 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
2020-05-03 14:36:01,957 ERROR: Exception on /GlobalTalk [GET] [in C:\Users\User\Desktop\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\User\Desktop\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\Desktop\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\Desktop\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\Desktop\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\User\Desktop\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\Desktop\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\User\Desktop\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\User\Desktop\microblog\app\main\routes.py", line 210, in GlobalTalk
    GTFunction = GlobalTalk.query.all()
AttributeError: 'function' object has no attribute 'query'
2020-05-03 14:36:37,561 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:74]
