2022-03-02 09:52:57,167 ERROR: Exception on /Mobplanlist/2 [GET] [in /usr/local/lib/python3.7/site-packages/flask/app.py:1458]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ec2-user/environment/webApp/app/main/routes.py", line 184, in Mobplanlist
    return render_template('MobPlan.html', form=form, govlist=govlist,group2=group2, group=group, govlist_filter=govlist_filter)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 150, in render_template
    ctx.app,
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ec2-user/environment/webApp/app/templates/MobPlan.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/ec2-user/environment/webApp/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/usr/local/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/usr/local/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/usr/local/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/usr/local/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/home/ec2-user/environment/webApp/app/templates/MobPlan.html", line 142, in block 'content'
    <li class="page-item"> <a class="page-link" href="{{ url_for('index', page=govlist.prev_num) }}">Previous</a></li>
  File "/usr/local/lib/python3.7/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.7/site-packages/flask/helpers.py", line 326, in url_for
    endpoint, values, method=method, force_external=external
  File "/usr/local/lib/python3.7/site-packages/werkzeug/routing.py", line 2315, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index' with values ['page']. Did you mean 'main.index' instead?
2022-03-02 09:53:31,894 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:81]
2022-03-02 10:17:02,381 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:81]
2022-03-02 10:21:25,153 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:81]
2022-03-02 10:23:21,548 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:81]
2022-03-02 10:25:27,572 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:81]
2022-03-02 10:27:30,054 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:81]
2022-03-02 10:28:11,370 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:81]
2022-03-02 10:28:52,599 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:81]
2022-03-02 10:33:25,323 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:81]
2022-03-02 10:35:14,311 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:81]
2022-03-02 10:38:58,281 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:81]
2022-03-02 10:39:34,602 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:81]
2022-03-02 10:39:39,809 ERROR: Exception on /Mobplanlist [POST] [in /usr/local/lib/python3.7/site-packages/flask/app.py:1458]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ec2-user/environment/webApp/app/main/routes.py", line 183, in Mobplanlist
    govlist = Governmentfac.query.order_by(Governmentfac.id.asc()).paginate(page,pages,error_out=False)
AttributeError: type object 'Governmentfac' has no attribute 'id'
2022-03-02 10:41:18,788 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:81]
2022-03-02 10:43:29,000 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:81]
2022-03-02 10:44:30,908 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:81]
2022-03-02 10:51:43,347 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:81]
2022-03-02 10:53:51,430 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:81]
2022-03-02 10:55:30,102 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:81]
2022-03-02 10:58:49,685 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:81]
2022-03-02 10:58:52,679 ERROR: Exception on /Mobplanlist [POST] [in /usr/local/lib/python3.7/site-packages/flask/app.py:1458]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ec2-user/environment/webApp/app/main/routes.py", line 187, in Mobplanlist
    searchresults = govlist.query.filter(govlist.Venue_Name.like(Search)).paginate(per_page=pages, error_out=False) # LIKE: query.filter(User.name.like('%ednalan%'))
AttributeError: 'Pagination' object has no attribute 'Venue_Name'
2022-03-02 10:59:45,766 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:81]
2022-03-02 10:59:48,802 ERROR: Exception on /Mobplanlist [POST] [in /usr/local/lib/python3.7/site-packages/flask/app.py:1458]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ec2-user/environment/webApp/app/main/routes.py", line 187, in Mobplanlist
    govlist = govlist.query.filter(govlist.Venue_Name.like(Search)).paginate(per_page=pages, error_out=False) # LIKE: query.filter(User.name.like('%ednalan%'))
AttributeError: 'Pagination' object has no attribute 'Venue_Name'
2022-03-02 11:00:52,160 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:81]
2022-03-02 11:14:26,433 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:81]
2022-03-02 11:17:15,327 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:81]
2022-03-02 11:43:35,581 INFO: Microblog startup [in /home/ec2-user/environment/webApp/app/__init__.py:81]
